"""Tests for rules file generator."""

import pytest
from pathlib import Path

from charlie.rules import (
    generate_rules_file,
    generate_rules_for_agents,
    _format_command_reference,
    _extract_manual_additions,
)
from charlie.schema import CharlieConfig, ProjectConfig, Command, CommandScripts, RulesConfig
from charlie.agents.registry import get_agent_spec


def test_format_command_reference():
    """Test formatting a command as reference entry."""
    command = Command(
        name="init",
        description="Initialize feature",
        prompt="Test",
        scripts=CommandScripts(sh="init.sh", ps="init.ps1"),
    )

    result = _format_command_reference(command, "myapp")

    assert "### /myapp.init" in result
    assert "**Description**: Initialize feature" in result
    assert "**Usage**: `/myapp.init <input>`" in result
    assert "Bash: `init.sh`" in result
    assert "PowerShell: `init.ps1`" in result


def test_extract_manual_additions():
    """Test extracting manual additions from existing content."""
    content = """# Title

Some content

<!-- MANUAL ADDITIONS START -->
My custom rules here
More custom stuff
<!-- MANUAL ADDITIONS END -->

More content
"""

    result = _extract_manual_additions(content)
    assert "My custom rules here" in result
    assert "More custom stuff" in result


def test_extract_manual_additions_empty():
    """Test extracting from content without manual additions."""
    content = "# Title\n\nSome content"

    result = _extract_manual_additions(content)
    assert result == ""


def test_generate_rules_file(tmp_path):
    """Test generating a rules file."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        commands=[
            Command(
                name="init",
                description="Initialize",
                prompt="Test",
                scripts=CommandScripts(sh="init.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("windsurf")

    rules_path = generate_rules_file(config, "windsurf", agent_spec, str(tmp_path))

    # Check file was created
    assert Path(rules_path).exists()

    # Check content
    content = Path(rules_path).read_text()
    assert "# Development Guidelines" in content
    assert "Auto-generated by Charlie" in content
    assert "## Available Commands" in content
    assert "/test.init" in content
    assert "MANUAL ADDITIONS START" in content


def test_generate_rules_file_preserves_manual_additions(tmp_path):
    """Test that rules file preserves manual additions on regeneration."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        commands=[
            Command(
                name="init",
                description="Initialize",
                prompt="Test",
                scripts=CommandScripts(sh="init.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("windsurf")

    # First generation
    rules_path = generate_rules_file(config, "windsurf", agent_spec, str(tmp_path))

    # Add manual content
    content = Path(rules_path).read_text()
    content = content.replace(
        "<!-- MANUAL ADDITIONS START -->",
        "<!-- MANUAL ADDITIONS START -->\nMy custom rule\nAnother custom rule",
    )
    Path(rules_path).write_text(content)

    # Regenerate
    rules_path = generate_rules_file(config, "windsurf", agent_spec, str(tmp_path))

    # Check manual additions are preserved
    new_content = Path(rules_path).read_text()
    assert "My custom rule" in new_content
    assert "Another custom rule" in new_content


def test_generate_rules_file_custom_title(tmp_path):
    """Test generating rules file with custom title."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        rules=RulesConfig(title="Custom Title"),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("claude")
    rules_path = generate_rules_file(config, "claude", agent_spec, str(tmp_path))

    content = Path(rules_path).read_text()
    assert "# Custom Title" in content


def test_generate_rules_file_without_commands(tmp_path):
    """Test generating rules file without command list."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        rules=RulesConfig(include_commands=False),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("claude")
    rules_path = generate_rules_file(config, "claude", agent_spec, str(tmp_path))

    content = Path(rules_path).read_text()
    assert "## Available Commands" not in content
    assert "/test.test" not in content


def test_generate_rules_file_without_preserve(tmp_path):
    """Test generating rules file without manual preservation."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        rules=RulesConfig(preserve_manual=False),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("claude")
    rules_path = generate_rules_file(config, "claude", agent_spec, str(tmp_path))

    content = Path(rules_path).read_text()
    assert "MANUAL ADDITIONS START" not in content


def test_generate_rules_for_agents(tmp_path):
    """Test generating rules files for multiple agents."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    agent_specs = {
        "claude": get_agent_spec("claude"),
        "windsurf": get_agent_spec("windsurf"),
    }

    results = generate_rules_for_agents(
        config, ["claude", "windsurf"], agent_specs, str(tmp_path)
    )

    assert len(results) == 2
    assert "claude" in results
    assert "windsurf" in results

    # Check both files exist
    assert Path(results["claude"]).exists()
    assert Path(results["windsurf"]).exists()


def test_generate_rules_for_agents_skips_missing_rules_file(tmp_path):
    """Test that agents without rules_file are skipped."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    # Create a fake agent spec without rules_file
    agent_specs = {"fake": {"name": "Fake Agent", "command_dir": ".fake"}}

    results = generate_rules_for_agents(config, ["fake"], agent_specs, str(tmp_path))

    # Should not generate anything for agent without rules_file
    assert len(results) == 0


def test_rules_file_date_format(tmp_path):
    """Test that rules file includes properly formatted date."""
    config = CharlieConfig(
        version="1.0",
        project=ProjectConfig(name="test", command_prefix="test"),
        commands=[
            Command(
                name="test",
                description="Test",
                prompt="Test",
                scripts=CommandScripts(sh="test.sh"),
            )
        ],
    )

    agent_spec = get_agent_spec("claude")
    rules_path = generate_rules_file(config, "claude", agent_spec, str(tmp_path))

    content = Path(rules_path).read_text()
    # Check date format YYYY-MM-DD
    import re

    assert re.search(r"Last updated: \d{4}-\d{2}-\d{2}", content)

