"""Rules file generator for IDE-based agents."""

from datetime import datetime
from pathlib import Path
from typing import List
import re

from charlie.schema import CharlieConfig, Command


def _format_command_reference(command: Command, command_prefix: str) -> str:
    """Format a command as a reference entry.

    Args:
        command: Command definition
        command_prefix: Command prefix

    Returns:
        Formatted command reference
    """
    lines = [
        f"### /{command_prefix}.{command.name}",
        "",
        f"**Description**: {command.description}",
        "",
        f"**Usage**: `/{command_prefix}.{command.name} <input>`",
        "",
        "**Scripts**:",
    ]

    if command.scripts.sh:
        lines.append(f"- Bash: `{command.scripts.sh}`")
    if command.scripts.ps:
        lines.append(f"- PowerShell: `{command.scripts.ps}`")

    lines.append("")  # Empty line after each command

    return "\n".join(lines)


def _extract_manual_additions(existing_content: str) -> str:
    """Extract manual additions from existing rules file.

    Args:
        existing_content: Existing file content

    Returns:
        Content between manual addition markers, or empty string
    """
    pattern = r"<!-- MANUAL ADDITIONS START -->(.*?)<!-- MANUAL ADDITIONS END -->"
    match = re.search(pattern, existing_content, re.DOTALL)

    if match:
        return match.group(1).strip()

    return ""


def generate_rules_file(
    config: CharlieConfig, agent_name: str, agent_spec: dict, output_dir: str
) -> str:
    """Generate rules file for an agent.

    Args:
        config: Charlie configuration
        agent_name: Name of the agent
        agent_spec: Agent specification from registry
        output_dir: Base output directory

    Returns:
        Path to generated rules file
    """
    rules_path = Path(output_dir) / agent_spec["rules_file"]
    rules_path.parent.mkdir(parents=True, exist_ok=True)

    # Check if file exists to preserve manual additions
    manual_additions = ""
    if rules_path.exists():
        existing_content = rules_path.read_text(encoding="utf-8")
        manual_additions = _extract_manual_additions(existing_content)

    # Build rules content
    title = config.rules.title
    current_date = datetime.now().strftime("%Y-%m-%d")

    lines = [
        f"# {title}",
        "",
        f"Auto-generated by Charlie from configuration",
        f"Last updated: {current_date}",
        "",
    ]

    # Add commands list if configured
    if config.rules.include_commands:
        lines.append("## Available Commands")
        lines.append("")
        for command in config.commands:
            lines.append(
                f"- `/{config.project.command_prefix}.{command.name}` - {command.description}"
            )
        lines.append("")

        # Add detailed command reference
        lines.append("## Command Reference")
        lines.append("")
        for command in config.commands:
            lines.append(_format_command_reference(command, config.project.command_prefix))

    # Add manual additions section if preserve_manual is enabled
    if config.rules.preserve_manual:
        lines.append("<!-- MANUAL ADDITIONS START -->")
        if manual_additions:
            lines.append(manual_additions)
        else:
            lines.append("<!-- Add your custom rules here - they will be preserved on regeneration -->")
        lines.append("<!-- MANUAL ADDITIONS END -->")

    content = "\n".join(lines)

    # Write to file
    rules_path.write_text(content, encoding="utf-8")

    return str(rules_path)


def generate_rules_for_agents(
    config: CharlieConfig, agents: List[str], agent_specs: dict, output_dir: str
) -> dict:
    """Generate rules files for multiple agents.

    Args:
        config: Charlie configuration
        agents: List of agent names
        agent_specs: Dictionary of agent specifications
        output_dir: Base output directory

    Returns:
        Dictionary mapping agent names to generated rules file paths
    """
    results = {}

    for agent_name in agents:
        if agent_name in agent_specs:
            agent_spec = agent_specs[agent_name]
            if "rules_file" in agent_spec:
                rules_path = generate_rules_file(config, agent_name, agent_spec, output_dir)
                results[agent_name] = rules_path

    return results

