"""Rules file generator for IDE-based agents."""

import re
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from charlie.schema import AgentSpec, CharlieConfig, Command, RulesSection


def _format_command_reference(command: Command, command_prefix: str) -> str:
    """Format a command as a reference entry.

    Args:
        command: Command definition
        command_prefix: Command prefix

    Returns:
        Formatted command reference
    """
    lines = [
        f"### /{command_prefix}.{command.name}",
        "",
        f"**Description**: {command.description}",
        "",
        f"**Usage**: `/{command_prefix}.{command.name} <input>`",
        "",
        "**Scripts**:",
    ]

    if command.scripts:
        if command.scripts.sh:
            lines.append(f"- Bash: `{command.scripts.sh}`")
        if command.scripts.ps:
            lines.append(f"- PowerShell: `{command.scripts.ps}`")
    else:
        lines.append("- No scripts (prompt only)")

    lines.append("")

    return "\n".join(lines)


def _extract_manual_additions(existing_content: str) -> str:
    """Extract manual additions from existing rules file.

    Args:
        existing_content: Existing file content

    Returns:
        Content between manual addition markers, or empty string
    """
    pattern = r"<!-- MANUAL ADDITIONS START -->(.*?)<!-- MANUAL ADDITIONS END -->"
    match = re.search(pattern, existing_content, re.DOTALL)

    if match:
        return match.group(1).strip()

    return ""


def _extract_frontmatter_fields(section: RulesSection) -> dict[str, Any]:
    """Extract agent-specific frontmatter fields from a rules section.

    Args:
        section: Rules section with possible agent-specific fields

    Returns:
        Dictionary of frontmatter fields (excluding core Charlie fields)
    """
    section_dict = section.model_dump()

    core_fields = {"title", "content", "order"}
    frontmatter = {k: v for k, v in section_dict.items() if k not in core_fields and v is not None}

    return frontmatter


def _format_frontmatter(frontmatter: dict[str, Any]) -> str:
    """Format frontmatter as YAML for markdown files.

    Args:
        frontmatter: Dictionary of frontmatter fields

    Returns:
        Formatted YAML frontmatter string
    """
    if not frontmatter:
        return ""

    yaml_str = yaml.dump(frontmatter, default_flow_style=False, sort_keys=False)
    return f"---\n{yaml_str}---\n\n"


def _transform_path_placeholders(text: str, agent_spec: AgentSpec, root_dir: str = ".") -> str:
    """Replace path placeholders in text with agent-specific paths.

    Args:
        text: Text with potential path placeholders
        agent_spec: Agent specification from registry
        root_dir: Root directory where charlie.yaml is located

    Returns:
        Text with resolved path placeholders
    """
    text = text.replace("{{root}}", root_dir)

    agent_dir = Path(agent_spec.command_dir).parent
    text = text.replace("{{agent_dir}}", str(agent_dir))

    commands_dir = agent_spec.command_dir
    text = text.replace("{{commands_dir}}", commands_dir)

    rules_dir = str(Path(agent_spec.rules_file).parent)
    text = text.replace("{{rules_dir}}", rules_dir)

    return text


def _generate_merged_rules(
    config: CharlieConfig,
    agent_name: str,
    agent_spec: AgentSpec,
    output_dir: str,
    root_dir: str = ".",
) -> str:
    """Generate a single merged rules file with all sections.

    Args:
        config: Charlie configuration
        agent_name: Name of the agent
        agent_spec: Agent specification from registry
        output_dir: Base output directory
        root_dir: Root directory where charlie.yaml is located

    Returns:
        Path to generated rules file
    """
    rules_path = Path(output_dir) / agent_spec.rules_file
    rules_path.parent.mkdir(parents=True, exist_ok=True)

    manual_additions = ""
    if rules_path.exists():
        existing_content = rules_path.read_text(encoding="utf-8")
        manual_additions = _extract_manual_additions(existing_content)

    frontmatter = {}
    if config.rules and config.rules.sections:
        sorted_sections = sorted(
            config.rules.sections, key=lambda s: (s.order if s.order is not None else 999, s.title)
        )
        if sorted_sections:
            frontmatter = _extract_frontmatter_fields(sorted_sections[0])

    title = config.rules.title if config.rules else "Development Guidelines"
    include_commands = config.rules.include_commands if config.rules else True
    preserve_manual = config.rules.preserve_manual if config.rules else True
    current_date = datetime.now().strftime("%Y-%m-%d")

    content_parts = []

    if frontmatter:
        content_parts.append(_format_frontmatter(frontmatter))

    lines = [
        f"# {title}",
        "",
        "Auto-generated by Charlie from configuration",
        f"Last updated: {current_date}",
        "",
    ]

    if config.rules and config.rules.sections:
        sorted_sections = sorted(
            config.rules.sections, key=lambda s: (s.order if s.order is not None else 999, s.title)
        )
        for section in sorted_sections:
            lines.append(f"## {section.title}")
            lines.append("")
            content = _transform_path_placeholders(section.content, agent_spec, root_dir)
            lines.append(content)
            lines.append("")

    if include_commands and config.commands:
        lines.append("## Available Commands")
        lines.append("")
        if config.project and config.project.command_prefix:
            for command in config.commands:
                lines.append(
                    f"- `/{config.project.command_prefix}.{command.name}` - {command.description}"
                )
            lines.append("")

            lines.append("## Command Reference")
            lines.append("")
            for command in config.commands:
                lines.append(_format_command_reference(command, config.project.command_prefix))

    if preserve_manual:
        lines.append("<!-- MANUAL ADDITIONS START -->")
        if manual_additions:
            lines.append(manual_additions)
        else:
            lines.append(
                "<!-- Add your custom rules here - they will be preserved on regeneration -->"
            )
        lines.append("<!-- MANUAL ADDITIONS END -->")

    content_parts.append("\n".join(lines))
    content = "".join(content_parts)

    rules_path.write_text(content, encoding="utf-8")

    return str(rules_path)


def _generate_separate_rules(
    config: CharlieConfig,
    agent_name: str,
    agent_spec: AgentSpec,
    output_dir: str,
    root_dir: str = ".",
) -> list[str]:
    """Generate separate rules files (one per section).

    Args:
        config: Charlie configuration
        agent_name: Name of the agent
        agent_spec: Agent specification from registry
        output_dir: Base output directory
        root_dir: Root directory where charlie.yaml is located

    Returns:
        List of paths to generated rules files
    """
    generated_files: list[str] = []

    if not config.rules or not config.rules.sections:
        return generated_files

    rules_file_path = Path(agent_spec.rules_file)
    rules_dir = Path(output_dir) / rules_file_path.parent
    rules_dir.mkdir(parents=True, exist_ok=True)

    sorted_sections = sorted(
        config.rules.sections, key=lambda s: (s.order if s.order is not None else 999, s.title)
    )

    for section in sorted_sections:
        filename = section.title.lower().replace(" ", "-").replace("/", "-") + ".md"
        section_path = rules_dir / filename

        frontmatter = _extract_frontmatter_fields(section)

        content_parts = []

        if frontmatter:
            content_parts.append(_format_frontmatter(frontmatter))

        content_text = _transform_path_placeholders(section.content, agent_spec, root_dir)
        lines = [
            f"# {section.title}",
            "",
            "Auto-generated by Charlie from configuration",
            f"Last updated: {datetime.now().strftime('%Y-%m-%d')}",
            "",
            content_text,
        ]

        content_parts.append("\n".join(lines))
        content = "".join(content_parts)

        section_path.write_text(content, encoding="utf-8")
        generated_files.append(str(section_path))

    return generated_files


def generate_rules_for_agents(
    config: CharlieConfig,
    agent_name: str,
    agent_spec: AgentSpec,
    output_dir: str,
    mode: str = "merged",
    root_dir: str = ".",
) -> list[str]:
    """Generate rules files for multiple agents.

    Args:
        config: Charlie configuration
        agent_name: Agent name
        agent_spec: Agent specifications
        output_dir: Base output directory
        mode: "merged" (single file) or "separate" (one file per section)
        root_dir: Root directory where charlie.yaml is located

    Returns:
        List of paths to generated rules files
    """
    if mode == "separate" and config.rules and config.rules.sections:
        return _generate_separate_rules(config, agent_name, agent_spec, output_dir, root_dir)
    else:
        return [_generate_merged_rules(config, agent_name, agent_spec, output_dir, root_dir)]
