from pathlib import Path
from typing import final

from charlie.assets_manager import AssetsManager
from charlie.configurators.agent_configurator import AgentConfigurator
from charlie.enums import RuleMode
from charlie.markdown_generator import MarkdownGenerator
from charlie.mcp_server_generator import MCPServerGenerator
from charlie.schema import Agent, Command, MCPServer, Project, Rule
from charlie.tracker import Tracker


@final
class OpencodeConfigurator(AgentConfigurator):
    __ALLOWED_COMMAND_METADATA = ["description"]
    __ALLOWED_INSTRUCTION_METADATA = ["description"]

    def __init__(
        self,
        agent: Agent,
        project: Project,
        tracker: Tracker,
        markdown_generator: MarkdownGenerator,
        mcp_server_generator: MCPServerGenerator,
        assets_manager: AssetsManager,
    ):
        self.agent = agent
        self.project = project
        self.tracker = tracker
        self.markdown_generator = markdown_generator
        self.mcp_server_generator = mcp_server_generator
        self.assets_manager = assets_manager

    def commands(self, commands: list[Command]) -> None:
        prompts_dir = Path(self.project.dir) / self.agent.commands_dir
        prompts_dir.mkdir(parents=True, exist_ok=True)

        for command in commands:
            name = command.name
            filename = f"{name}.{self.agent.commands_extension}"
            if self.project.namespace is not None:
                filename = f"{self.project.namespace}-{filename}"

            command_file = prompts_dir / filename
            self.markdown_generator.generate(
                file=command_file,
                body=command.prompt,
                metadata={"description": command.description, **command.metadata},
                allowed_metadata=self.__ALLOWED_COMMAND_METADATA,
            )

            self.tracker.track(f"Created {command_file}")

    def rules(self, rules: list[Rule], mode: RuleMode) -> None:
        if not rules:
            return

        if mode == RuleMode.MERGED:
            instructions_file = Path(self.project.dir) / self.agent.rules_file
            instructions_file.parent.mkdir(parents=True, exist_ok=True)

            body = f"# {self.project.name}\n\n"

            for rule in rules:
                body += f"## {rule.description}\n\n"
                body += f"{rule.prompt}\n\n"

            self.markdown_generator.generate(file=instructions_file, body=body.rstrip())
            self.tracker.track(f"Created {instructions_file}")
            return

        rules_dir = Path(self.project.dir) / self.agent.rules_dir
        rules_dir.mkdir(parents=True, exist_ok=True)

        body = f"# {self.project.name}\n\n"

        for rule in rules:
            filename = f"{rule.name}.{self.agent.rules_extension}"
            if self.project.namespace is not None:
                filename = f"{self.project.namespace}-{filename}"

            rule_file = rules_dir / filename
            self.markdown_generator.generate(
                file=rule_file,
                body=rule.prompt,
                metadata={"description": rule.description, **rule.metadata},
                allowed_metadata=self.__ALLOWED_INSTRUCTION_METADATA,
            )

            relative_path = f"{self.agent.rules_dir}/{filename}"
            body += f"## {rule.description}\n\n"
            body += f"See @{relative_path}\n\n"

            self.tracker.track(f"Created {rule_file}")

        instructions_file = Path(self.project.dir) / self.agent.rules_file
        self.markdown_generator.generate(file=instructions_file, body=body.rstrip())
        self.tracker.track(f"Created {instructions_file}")

    def mcp_servers(self, mcp_servers: list[MCPServer]) -> None:
        if not mcp_servers:
            return

        file = Path(self.project.dir) / Path(self.agent.mcp_file)
        self.mcp_server_generator.generate(file, mcp_servers)

    def assets(self, assets: list[str]) -> None:
        if not assets:
            return

        source_base = Path(self.project.dir) / ".charlie" / "assets"
        destination_base = Path(self.project.dir) / self.agent.dir / "assets"
        self.assets_manager.copy_assets(assets, source_base, destination_base)

    def ignore_file(self, patterns: list[str]) -> None:
        if self.agent.ignore_file is None:
            return

        ignore_file_path = Path(self.project.dir) / self.agent.ignore_file

        # Create the ignore file content
        content_lines = [
            "# Auto-generated by Charlie",
            "# Add patterns to ignore files and directories",
            "",
        ]

        for pattern in patterns:
            content_lines.append(pattern)

        content = "\n".join(content_lines) + "\n"

        # Ensure parent directory exists
        ignore_file_path.parent.mkdir(parents=True, exist_ok=True)

        # Write the ignore file
        with open(ignore_file_path, "w", encoding="utf-8") as f:
            f.write(content)

        self.tracker.track(f"Generated ignore file: {ignore_file_path}")
